
# cargo-vet audits file

[[audits.bitflags]]
criteria = "safe-to-deploy"
version = "2.8.0"
notes = "Test for running cargo vet"

[[audits.hpack]]
criteria = "safe-to-deploy"
version = "0.3.0"
notes = "Test for running cargo vet"

[[audits.log]]
criteria = "safe-to-deploy"
version = "0.3.9"
notes = "Approved after manual review"

[[audits.log]]
criteria = "safe-to-deploy"
version = "0.4.25"
notes = "Approved after manual review"
