[package]
name = "rpn"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.32.0", features = ["bitflags"] }

# Vulnerability
json = { version = "0.12.4"}

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:rpn"

[package.metadata.component.dependencies]

[package.metadata.component.target]
path = "../wit/rpn"
world = "calculator"
