
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.bitflags]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-rt]]
version = "0.32.0"
criteria = "safe-to-deploy"
